# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def core
  pod 'RxSwift' 
  pod 'RxCocoa'
  pod 'RxOptional'
  pod 'RxBinding'
  pod 'RxGesture'
  pod 'RxDataSources'
  
  pod 'Then'
end

def network
  pod 'Moya/RxSwift', '14.0.0-alpha.2'
  pod 'AlamofireImage', '4.0.0-beta.3'
end

target 'YouBikeKit' do 
  use_frameworks!
  core
  network
end


target 'YouBike' do
  use_frameworks!
  core
  network

  # UI
  pod 'SnapKit'
  pod 'Pulley'
end

target 'Nearby' do
  use_frameworks!
  core
  network
end

target 'NearbyUI' do
  use_frameworks!
  core
  pod 'RxCoreLocation'
end
